notifications:
  slack: wsi-t113:SRHSOd3CgFDUwFxqv8SCXuIf
  email: false

sudo: false

language: ruby

services:
 - docker

script:
 - while sleep 9m; do echo "=====[ $SECONDS seconds, docker still building... ]====="; done &
 - echo 'Build and check docker image'
 - docker build --target builder -t builder .

